import { AppProvider } from '../context/AppContext';
import Link from 'next/link';
import { useAppContext } from '../context/AppContext';
import { Metadata } from 'next'
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export const metadata: Metadata = {
  title: 'Block Finder',
  description: 'HTX',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

        <AppProvider>
          <body>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </body>
        </AppProvider>
    </html>
  )
}
