"""uniqueness of database

Revision ID: 321a878cd2fa
Revises: b804c73d94c0
Create Date: 2024-09-16 20:03:53.384401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '321a878cd2fa'
down_revision: Union[str, None] = 'b804c73d94c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('cropped_image_analyses')
    # op.drop_table('polygons-old')
    op.drop_index('ix_cropped_images_filename', table_name='cropped_images')
    op.create_index(op.f('ix_cropped_images_filename'), 'cropped_images', ['filename'], unique=False)
    op.drop_constraint('cropped_images_polygon_id_fkey', 'cropped_images', type_='foreignkey')
    op.create_foreign_key(None, 'cropped_images', 'polygons', ['polygon_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_images_filename', table_name='images')
    op.create_index(op.f('ix_images_filename'), 'images', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_filename'), table_name='images')
    op.create_index('ix_images_filename', 'images', ['filename'], unique=True)
    op.drop_constraint(None, 'cropped_images', type_='foreignkey')
    op.create_foreign_key('cropped_images_polygon_id_fkey', 'cropped_images', 'polygons', ['polygon_id'], ['id'])
    op.drop_index(op.f('ix_cropped_images_filename'), table_name='cropped_images')
    op.create_index('ix_cropped_images_filename', 'cropped_images', ['filename'], unique=True)
    # op.create_table('cropped_image_analyses',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('cropped_image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='cropped_image_analyses_pkey')
    # )
    # ### end Alembic commands ###
